name: SAST Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: sast-scan
      # you may pin to the exact commit or the version.
      # uses: AppThreat/sast-scan-action@4d0f956e6ba3c940a22679fd8fe7cb2e755f3d96
      uses: AppThreat/sast-scan-action@1.0.2
      with:
        # Source directory to scan. Defaults to workspace
        src: /github/workspace
        # Output directory for the generated reports. Defaults to reports
        output: /github/workspace/reports
        # Project type. Eg: java, python, nodejs. Comma separated values allowed.
        type: java
